/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CollegeRouteImport } from './routes/college'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as StudentRouteImport } from './routes/student'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAssessmentsRouteImport } from './routes/admin.assessments'
import { Route as AdminCollegesRouteImport } from './routes/admin.colleges'
import { Route as AdminIndustriesRouteImport } from './routes/admin.industries'
import { Route as AdminOpportunitiesRouteImport } from './routes/admin.opportunities'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSkillsRouteImport } from './routes/admin.skills'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CollegeIndexRouteImport } from './routes/college.index'
import { Route as CollegeAnalyticsRouteImport } from './routes/college.analytics'
import { Route as CollegeDemandRouteImport } from './routes/college.demand'
import { Route as CollegeDrivesRouteImport } from './routes/college.drives'
import { Route as CollegeGapsRouteImport } from './routes/college.gaps'
import { Route as CollegeIntelligenceRouteImport } from './routes/college.intelligence'
import { Route as CollegeInternshipsRouteImport } from './routes/college.internships'
import { Route as CollegeNotificationsRouteImport } from './routes/college.notifications'
import { Route as CollegeOnboardingRouteImport } from './routes/college.onboarding'
import { Route as CollegeSettingsRouteImport } from './routes/college.settings'
import { Route as CollegeStudentsRouteImport } from './routes/college.students'
import { Route as CollegeTrainingRouteImport } from './routes/college.training'
import { Route as RecruiterIndexRouteImport } from './routes/recruiter.index'
import { Route as RecruiterApplicationsRouteImport } from './routes/recruiter.applications'
import { Route as RecruiterCompanyRouteImport } from './routes/recruiter.company'
import { Route as RecruiterDemandRouteImport } from './routes/recruiter.demand'
import { Route as RecruiterNotificationsRouteImport } from './routes/recruiter.notifications'
import { Route as RecruiterOnboardingRouteImport } from './routes/recruiter.onboarding'
import { Route as RecruiterPipelineRouteImport } from './routes/recruiter.pipeline'
import { Route as RecruiterPostRouteImport } from './routes/recruiter.post'
import { Route as RecruiterSettingsRouteImport } from './routes/recruiter.settings'
import { Route as RecruiterTalentRouteImport } from './routes/recruiter.talent'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentApplicationsRouteImport } from './routes/student.applications'
import { Route as StudentAssessmentsRouteImport } from './routes/student.assessments'
import { Route as StudentInternshipsRouteImport } from './routes/student.internships'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentOnboardingRouteImport } from './routes/student.onboarding'
import { Route as StudentPassportRouteImport } from './routes/student.passport'
import { Route as StudentProjectsRouteImport } from './routes/student.projects'
import { Route as StudentReadinessRouteImport } from './routes/student.readiness'
import { Route as StudentRoadmapRouteImport } from './routes/student.roadmap'
import { Route as StudentSettingsRouteImport } from './routes/student.settings'
import { Route as StudentSkillGapRouteImport } from './routes/student.skill-gap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeRoute = CollegeRouteImport.update({
  id: '/college',
  path: '/college',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssessmentsRoute = AdminAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollegesRoute = AdminCollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIndustriesRoute = AdminIndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpportunitiesRoute = AdminOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSkillsRoute = AdminSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CollegeIndexRoute = CollegeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollegeRoute,
} as any)
const CollegeAnalyticsRoute = CollegeAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CollegeRoute,
} as any)
const CollegeDemandRoute = CollegeDemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => CollegeRoute,
} as any)
const CollegeDrivesRoute = CollegeDrivesRouteImport.update({
  id: '/drives',
  path: '/drives',
  getParentRoute: () => CollegeRoute,
} as any)
const CollegeGapsRoute = CollegeGapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => CollegeRoute,
} as any)
const CollegeIntelligenceRoute = CollegeIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => CollegeRoute,
} as any)
const CollegeInternshipsRoute = CollegeInternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => CollegeRoute,
} as any)
const CollegeNotificationsRoute = CollegeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CollegeRoute,
} as any)
const CollegeOnboardingRoute = CollegeOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => CollegeRoute,
} as any)
const CollegeSettingsRoute = CollegeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CollegeRoute,
} as any)
const CollegeStudentsRoute = CollegeStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => CollegeRoute,
} as any)
const CollegeTrainingRoute = CollegeTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => CollegeRoute,
} as any)
const RecruiterIndexRoute = RecruiterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterApplicationsRoute = RecruiterApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterCompanyRoute = RecruiterCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterDemandRoute = RecruiterDemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterNotificationsRoute = RecruiterNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterOnboardingRoute = RecruiterOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterPipelineRoute = RecruiterPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterPostRoute = RecruiterPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterSettingsRoute = RecruiterSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterTalentRoute = RecruiterTalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => RecruiterRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentApplicationsRoute = StudentApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssessmentsRoute = StudentAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => StudentRoute,
} as any)
const StudentInternshipsRoute = StudentInternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentOnboardingRoute = StudentOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPassportRoute = StudentPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProjectsRoute = StudentProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => StudentRoute,
} as any)
const StudentReadinessRoute = StudentReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => StudentRoute,
} as any)
const StudentRoadmapRoute = StudentRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSkillGapRoute = StudentSkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/college': typeof CollegeRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/recruiter': typeof RecruiterRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/industries': typeof AdminIndustriesRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/college/analytics': typeof CollegeAnalyticsRoute
  '/college/demand': typeof CollegeDemandRoute
  '/college/drives': typeof CollegeDrivesRoute
  '/college/gaps': typeof CollegeGapsRoute
  '/college/intelligence': typeof CollegeIntelligenceRoute
  '/college/internships': typeof CollegeInternshipsRoute
  '/college/notifications': typeof CollegeNotificationsRoute
  '/college/onboarding': typeof CollegeOnboardingRoute
  '/college/settings': typeof CollegeSettingsRoute
  '/college/students': typeof CollegeStudentsRoute
  '/college/training': typeof CollegeTrainingRoute
  '/recruiter/applications': typeof RecruiterApplicationsRoute
  '/recruiter/company': typeof RecruiterCompanyRoute
  '/recruiter/demand': typeof RecruiterDemandRoute
  '/recruiter/notifications': typeof RecruiterNotificationsRoute
  '/recruiter/onboarding': typeof RecruiterOnboardingRoute
  '/recruiter/pipeline': typeof RecruiterPipelineRoute
  '/recruiter/post': typeof RecruiterPostRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/recruiter/talent': typeof RecruiterTalentRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/internships': typeof StudentInternshipsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/onboarding': typeof StudentOnboardingRoute
  '/student/passport': typeof StudentPassportRoute
  '/student/projects': typeof StudentProjectsRoute
  '/student/readiness': typeof StudentReadinessRoute
  '/student/roadmap': typeof StudentRoadmapRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/skill-gap': typeof StudentSkillGapRoute
  '/admin/': typeof AdminIndexRoute
  '/college/': typeof CollegeIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/industries': typeof AdminIndustriesRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/college/analytics': typeof CollegeAnalyticsRoute
  '/college/demand': typeof CollegeDemandRoute
  '/college/drives': typeof CollegeDrivesRoute
  '/college/gaps': typeof CollegeGapsRoute
  '/college/intelligence': typeof CollegeIntelligenceRoute
  '/college/internships': typeof CollegeInternshipsRoute
  '/college/notifications': typeof CollegeNotificationsRoute
  '/college/onboarding': typeof CollegeOnboardingRoute
  '/college/settings': typeof CollegeSettingsRoute
  '/college/students': typeof CollegeStudentsRoute
  '/college/training': typeof CollegeTrainingRoute
  '/recruiter/applications': typeof RecruiterApplicationsRoute
  '/recruiter/company': typeof RecruiterCompanyRoute
  '/recruiter/demand': typeof RecruiterDemandRoute
  '/recruiter/notifications': typeof RecruiterNotificationsRoute
  '/recruiter/onboarding': typeof RecruiterOnboardingRoute
  '/recruiter/pipeline': typeof RecruiterPipelineRoute
  '/recruiter/post': typeof RecruiterPostRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/recruiter/talent': typeof RecruiterTalentRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/internships': typeof StudentInternshipsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/onboarding': typeof StudentOnboardingRoute
  '/student/passport': typeof StudentPassportRoute
  '/student/projects': typeof StudentProjectsRoute
  '/student/readiness': typeof StudentReadinessRoute
  '/student/roadmap': typeof StudentRoadmapRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/skill-gap': typeof StudentSkillGapRoute
  '/admin': typeof AdminIndexRoute
  '/college': typeof CollegeIndexRoute
  '/recruiter': typeof RecruiterIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/college': typeof CollegeRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/recruiter': typeof RecruiterRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/industries': typeof AdminIndustriesRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/college/analytics': typeof CollegeAnalyticsRoute
  '/college/demand': typeof CollegeDemandRoute
  '/college/drives': typeof CollegeDrivesRoute
  '/college/gaps': typeof CollegeGapsRoute
  '/college/intelligence': typeof CollegeIntelligenceRoute
  '/college/internships': typeof CollegeInternshipsRoute
  '/college/notifications': typeof CollegeNotificationsRoute
  '/college/onboarding': typeof CollegeOnboardingRoute
  '/college/settings': typeof CollegeSettingsRoute
  '/college/students': typeof CollegeStudentsRoute
  '/college/training': typeof CollegeTrainingRoute
  '/recruiter/applications': typeof RecruiterApplicationsRoute
  '/recruiter/company': typeof RecruiterCompanyRoute
  '/recruiter/demand': typeof RecruiterDemandRoute
  '/recruiter/notifications': typeof RecruiterNotificationsRoute
  '/recruiter/onboarding': typeof RecruiterOnboardingRoute
  '/recruiter/pipeline': typeof RecruiterPipelineRoute
  '/recruiter/post': typeof RecruiterPostRoute
  '/recruiter/settings': typeof RecruiterSettingsRoute
  '/recruiter/talent': typeof RecruiterTalentRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/internships': typeof StudentInternshipsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/onboarding': typeof StudentOnboardingRoute
  '/student/passport': typeof StudentPassportRoute
  '/student/projects': typeof StudentProjectsRoute
  '/student/readiness': typeof StudentReadinessRoute
  '/student/roadmap': typeof StudentRoadmapRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/skill-gap': typeof StudentSkillGapRoute
  '/admin/': typeof AdminIndexRoute
  '/college/': typeof CollegeIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/college'
    | '/contact'
    | '/privacy'
    | '/recruiter'
    | '/student'
    | '/terms'
    | '/admin/assessments'
    | '/admin/colleges'
    | '/admin/industries'
    | '/admin/opportunities'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/students'
    | '/admin/users'
    | '/college/analytics'
    | '/college/demand'
    | '/college/drives'
    | '/college/gaps'
    | '/college/intelligence'
    | '/college/internships'
    | '/college/notifications'
    | '/college/onboarding'
    | '/college/settings'
    | '/college/students'
    | '/college/training'
    | '/recruiter/applications'
    | '/recruiter/company'
    | '/recruiter/demand'
    | '/recruiter/notifications'
    | '/recruiter/onboarding'
    | '/recruiter/pipeline'
    | '/recruiter/post'
    | '/recruiter/settings'
    | '/recruiter/talent'
    | '/student/applications'
    | '/student/assessments'
    | '/student/internships'
    | '/student/notifications'
    | '/student/onboarding'
    | '/student/passport'
    | '/student/projects'
    | '/student/readiness'
    | '/student/roadmap'
    | '/student/settings'
    | '/student/skill-gap'
    | '/admin/'
    | '/college/'
    | '/recruiter/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/admin/assessments'
    | '/admin/colleges'
    | '/admin/industries'
    | '/admin/opportunities'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/students'
    | '/admin/users'
    | '/college/analytics'
    | '/college/demand'
    | '/college/drives'
    | '/college/gaps'
    | '/college/intelligence'
    | '/college/internships'
    | '/college/notifications'
    | '/college/onboarding'
    | '/college/settings'
    | '/college/students'
    | '/college/training'
    | '/recruiter/applications'
    | '/recruiter/company'
    | '/recruiter/demand'
    | '/recruiter/notifications'
    | '/recruiter/onboarding'
    | '/recruiter/pipeline'
    | '/recruiter/post'
    | '/recruiter/settings'
    | '/recruiter/talent'
    | '/student/applications'
    | '/student/assessments'
    | '/student/internships'
    | '/student/notifications'
    | '/student/onboarding'
    | '/student/passport'
    | '/student/projects'
    | '/student/readiness'
    | '/student/roadmap'
    | '/student/settings'
    | '/student/skill-gap'
    | '/admin'
    | '/college'
    | '/recruiter'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/college'
    | '/contact'
    | '/privacy'
    | '/recruiter'
    | '/student'
    | '/terms'
    | '/admin/assessments'
    | '/admin/colleges'
    | '/admin/industries'
    | '/admin/opportunities'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/students'
    | '/admin/users'
    | '/college/analytics'
    | '/college/demand'
    | '/college/drives'
    | '/college/gaps'
    | '/college/intelligence'
    | '/college/internships'
    | '/college/notifications'
    | '/college/onboarding'
    | '/college/settings'
    | '/college/students'
    | '/college/training'
    | '/recruiter/applications'
    | '/recruiter/company'
    | '/recruiter/demand'
    | '/recruiter/notifications'
    | '/recruiter/onboarding'
    | '/recruiter/pipeline'
    | '/recruiter/post'
    | '/recruiter/settings'
    | '/recruiter/talent'
    | '/student/applications'
    | '/student/assessments'
    | '/student/internships'
    | '/student/notifications'
    | '/student/onboarding'
    | '/student/passport'
    | '/student/projects'
    | '/student/readiness'
    | '/student/roadmap'
    | '/student/settings'
    | '/student/skill-gap'
    | '/admin/'
    | '/college/'
    | '/recruiter/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CollegeRoute: typeof CollegeRouteWithChildren
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  RecruiterRoute: typeof RecruiterRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college': {
      id: '/college'
      path: '/college'
      fullPath: '/college'
      preLoaderRoute: typeof CollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assessments': {
      id: '/admin/assessments'
      path: '/assessments'
      fullPath: '/admin/assessments'
      preLoaderRoute: typeof AdminAssessmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colleges': {
      id: '/admin/colleges'
      path: '/colleges'
      fullPath: '/admin/colleges'
      preLoaderRoute: typeof AdminCollegesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/industries': {
      id: '/admin/industries'
      path: '/industries'
      fullPath: '/admin/industries'
      preLoaderRoute: typeof AdminIndustriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/opportunities': {
      id: '/admin/opportunities'
      path: '/opportunities'
      fullPath: '/admin/opportunities'
      preLoaderRoute: typeof AdminOpportunitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/skills': {
      id: '/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AdminSkillsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/college/': {
      id: '/college/'
      path: '/'
      fullPath: '/college/'
      preLoaderRoute: typeof CollegeIndexRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/college/analytics': {
      id: '/college/analytics'
      path: '/analytics'
      fullPath: '/college/analytics'
      preLoaderRoute: typeof CollegeAnalyticsRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/college/demand': {
      id: '/college/demand'
      path: '/demand'
      fullPath: '/college/demand'
      preLoaderRoute: typeof CollegeDemandRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/college/drives': {
      id: '/college/drives'
      path: '/drives'
      fullPath: '/college/drives'
      preLoaderRoute: typeof CollegeDrivesRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/college/gaps': {
      id: '/college/gaps'
      path: '/gaps'
      fullPath: '/college/gaps'
      preLoaderRoute: typeof CollegeGapsRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/college/intelligence': {
      id: '/college/intelligence'
      path: '/intelligence'
      fullPath: '/college/intelligence'
      preLoaderRoute: typeof CollegeIntelligenceRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/college/internships': {
      id: '/college/internships'
      path: '/internships'
      fullPath: '/college/internships'
      preLoaderRoute: typeof CollegeInternshipsRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/college/notifications': {
      id: '/college/notifications'
      path: '/notifications'
      fullPath: '/college/notifications'
      preLoaderRoute: typeof CollegeNotificationsRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/college/onboarding': {
      id: '/college/onboarding'
      path: '/onboarding'
      fullPath: '/college/onboarding'
      preLoaderRoute: typeof CollegeOnboardingRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/college/settings': {
      id: '/college/settings'
      path: '/settings'
      fullPath: '/college/settings'
      preLoaderRoute: typeof CollegeSettingsRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/college/students': {
      id: '/college/students'
      path: '/students'
      fullPath: '/college/students'
      preLoaderRoute: typeof CollegeStudentsRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/college/training': {
      id: '/college/training'
      path: '/training'
      fullPath: '/college/training'
      preLoaderRoute: typeof CollegeTrainingRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/recruiter/': {
      id: '/recruiter/'
      path: '/'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof RecruiterIndexRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/applications': {
      id: '/recruiter/applications'
      path: '/applications'
      fullPath: '/recruiter/applications'
      preLoaderRoute: typeof RecruiterApplicationsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/company': {
      id: '/recruiter/company'
      path: '/company'
      fullPath: '/recruiter/company'
      preLoaderRoute: typeof RecruiterCompanyRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/demand': {
      id: '/recruiter/demand'
      path: '/demand'
      fullPath: '/recruiter/demand'
      preLoaderRoute: typeof RecruiterDemandRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/notifications': {
      id: '/recruiter/notifications'
      path: '/notifications'
      fullPath: '/recruiter/notifications'
      preLoaderRoute: typeof RecruiterNotificationsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/onboarding': {
      id: '/recruiter/onboarding'
      path: '/onboarding'
      fullPath: '/recruiter/onboarding'
      preLoaderRoute: typeof RecruiterOnboardingRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/pipeline': {
      id: '/recruiter/pipeline'
      path: '/pipeline'
      fullPath: '/recruiter/pipeline'
      preLoaderRoute: typeof RecruiterPipelineRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/post': {
      id: '/recruiter/post'
      path: '/post'
      fullPath: '/recruiter/post'
      preLoaderRoute: typeof RecruiterPostRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/settings': {
      id: '/recruiter/settings'
      path: '/settings'
      fullPath: '/recruiter/settings'
      preLoaderRoute: typeof RecruiterSettingsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/talent': {
      id: '/recruiter/talent'
      path: '/talent'
      fullPath: '/recruiter/talent'
      preLoaderRoute: typeof RecruiterTalentRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/applications': {
      id: '/student/applications'
      path: '/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof StudentApplicationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assessments': {
      id: '/student/assessments'
      path: '/assessments'
      fullPath: '/student/assessments'
      preLoaderRoute: typeof StudentAssessmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/internships': {
      id: '/student/internships'
      path: '/internships'
      fullPath: '/student/internships'
      preLoaderRoute: typeof StudentInternshipsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/onboarding': {
      id: '/student/onboarding'
      path: '/onboarding'
      fullPath: '/student/onboarding'
      preLoaderRoute: typeof StudentOnboardingRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/passport': {
      id: '/student/passport'
      path: '/passport'
      fullPath: '/student/passport'
      preLoaderRoute: typeof StudentPassportRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/projects': {
      id: '/student/projects'
      path: '/projects'
      fullPath: '/student/projects'
      preLoaderRoute: typeof StudentProjectsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/readiness': {
      id: '/student/readiness'
      path: '/readiness'
      fullPath: '/student/readiness'
      preLoaderRoute: typeof StudentReadinessRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/roadmap': {
      id: '/student/roadmap'
      path: '/roadmap'
      fullPath: '/student/roadmap'
      preLoaderRoute: typeof StudentRoadmapRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/skill-gap': {
      id: '/student/skill-gap'
      path: '/skill-gap'
      fullPath: '/student/skill-gap'
      preLoaderRoute: typeof StudentSkillGapRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAssessmentsRoute: typeof AdminAssessmentsRoute
  AdminCollegesRoute: typeof AdminCollegesRoute
  AdminIndustriesRoute: typeof AdminIndustriesRoute
  AdminOpportunitiesRoute: typeof AdminOpportunitiesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSkillsRoute: typeof AdminSkillsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssessmentsRoute: AdminAssessmentsRoute,
  AdminCollegesRoute: AdminCollegesRoute,
  AdminIndustriesRoute: AdminIndustriesRoute,
  AdminOpportunitiesRoute: AdminOpportunitiesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSkillsRoute: AdminSkillsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CollegeRouteChildren {
  CollegeAnalyticsRoute: typeof CollegeAnalyticsRoute
  CollegeDemandRoute: typeof CollegeDemandRoute
  CollegeDrivesRoute: typeof CollegeDrivesRoute
  CollegeGapsRoute: typeof CollegeGapsRoute
  CollegeIntelligenceRoute: typeof CollegeIntelligenceRoute
  CollegeInternshipsRoute: typeof CollegeInternshipsRoute
  CollegeNotificationsRoute: typeof CollegeNotificationsRoute
  CollegeOnboardingRoute: typeof CollegeOnboardingRoute
  CollegeSettingsRoute: typeof CollegeSettingsRoute
  CollegeStudentsRoute: typeof CollegeStudentsRoute
  CollegeTrainingRoute: typeof CollegeTrainingRoute
  CollegeIndexRoute: typeof CollegeIndexRoute
}

const CollegeRouteChildren: CollegeRouteChildren = {
  CollegeAnalyticsRoute: CollegeAnalyticsRoute,
  CollegeDemandRoute: CollegeDemandRoute,
  CollegeDrivesRoute: CollegeDrivesRoute,
  CollegeGapsRoute: CollegeGapsRoute,
  CollegeIntelligenceRoute: CollegeIntelligenceRoute,
  CollegeInternshipsRoute: CollegeInternshipsRoute,
  CollegeNotificationsRoute: CollegeNotificationsRoute,
  CollegeOnboardingRoute: CollegeOnboardingRoute,
  CollegeSettingsRoute: CollegeSettingsRoute,
  CollegeStudentsRoute: CollegeStudentsRoute,
  CollegeTrainingRoute: CollegeTrainingRoute,
  CollegeIndexRoute: CollegeIndexRoute,
}

const CollegeRouteWithChildren =
  CollegeRoute._addFileChildren(CollegeRouteChildren)

interface RecruiterRouteChildren {
  RecruiterApplicationsRoute: typeof RecruiterApplicationsRoute
  RecruiterCompanyRoute: typeof RecruiterCompanyRoute
  RecruiterDemandRoute: typeof RecruiterDemandRoute
  RecruiterNotificationsRoute: typeof RecruiterNotificationsRoute
  RecruiterOnboardingRoute: typeof RecruiterOnboardingRoute
  RecruiterPipelineRoute: typeof RecruiterPipelineRoute
  RecruiterPostRoute: typeof RecruiterPostRoute
  RecruiterSettingsRoute: typeof RecruiterSettingsRoute
  RecruiterTalentRoute: typeof RecruiterTalentRoute
  RecruiterIndexRoute: typeof RecruiterIndexRoute
}

const RecruiterRouteChildren: RecruiterRouteChildren = {
  RecruiterApplicationsRoute: RecruiterApplicationsRoute,
  RecruiterCompanyRoute: RecruiterCompanyRoute,
  RecruiterDemandRoute: RecruiterDemandRoute,
  RecruiterNotificationsRoute: RecruiterNotificationsRoute,
  RecruiterOnboardingRoute: RecruiterOnboardingRoute,
  RecruiterPipelineRoute: RecruiterPipelineRoute,
  RecruiterPostRoute: RecruiterPostRoute,
  RecruiterSettingsRoute: RecruiterSettingsRoute,
  RecruiterTalentRoute: RecruiterTalentRoute,
  RecruiterIndexRoute: RecruiterIndexRoute,
}

const RecruiterRouteWithChildren = RecruiterRoute._addFileChildren(
  RecruiterRouteChildren,
)

interface StudentRouteChildren {
  StudentApplicationsRoute: typeof StudentApplicationsRoute
  StudentAssessmentsRoute: typeof StudentAssessmentsRoute
  StudentInternshipsRoute: typeof StudentInternshipsRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentOnboardingRoute: typeof StudentOnboardingRoute
  StudentPassportRoute: typeof StudentPassportRoute
  StudentProjectsRoute: typeof StudentProjectsRoute
  StudentReadinessRoute: typeof StudentReadinessRoute
  StudentRoadmapRoute: typeof StudentRoadmapRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentSkillGapRoute: typeof StudentSkillGapRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentApplicationsRoute: StudentApplicationsRoute,
  StudentAssessmentsRoute: StudentAssessmentsRoute,
  StudentInternshipsRoute: StudentInternshipsRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentOnboardingRoute: StudentOnboardingRoute,
  StudentPassportRoute: StudentPassportRoute,
  StudentProjectsRoute: StudentProjectsRoute,
  StudentReadinessRoute: StudentReadinessRoute,
  StudentRoadmapRoute: StudentRoadmapRoute,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentSkillGapRoute: StudentSkillGapRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CollegeRoute: CollegeRouteWithChildren,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  RecruiterRoute: RecruiterRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
